name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    permissions:
      id-token: write
      packages: write
    env:
      PROJECT: Sitko.Blazor.CKEditor
      BUNDLE_PROJECT: Sitko.Blazor.CKEditor.Bundle
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare
        id: prep
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build bundle js
        working-directory: src/${{ env.BUNDLE_PROJECT }}/Web
        shell: bash
        run: |
          npm ci
          npm run prod
      - name: Create packages
        run: dotnet pack /p:Version=${{ steps.prep.outputs.version }} -c Release -o $(pwd)/packages
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Push to Nuget
        run: find packages -name *.nupkg -exec dotnet nuget push {} -s https://api.nuget.org/v3/index.json -k ${{ steps.login.outputs.NUGET_API_KEY }} \;

